rabbit1:
  image: fantuan/rabbitmq-server:3.7.0
  hostname: rabbit1.fantuan.io
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_DEFAULT_USER=luoxc
    - RABBITMQ_DEFAULT_PASS=luoxc
    
rabbit2:
  image: fantuan/rabbitmq-server:3.7.0
  hostname: rabbit2.fantuan.io
  links:
    - rabbit1
  environment:
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    - RAM_NODE=true
  ports:
    - "5673:5672"
    - "15673:15672"

rabbit3:
  image: fantuan/rabbitmq-server:3.7.0
  hostname: rabbit3.fantuan.io
  links:
    - rabbit1
    - rabbit2
  environment:
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
  ports:
    - "5674:5672"
    - "15674:15672"
